Shop/ViewModels/CarsListViewModel.cs
using Shop.Data.Models;
using System.Collections.Generic;

namespace Shop.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> allCars { get; set; }

        public string currentCategory { get; set; }
    }
}

Shop/ViewModels/HomeViewModel.cs
using Shop.Data.Models;
using System.Collections.Generic;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> FavouriteCars { get; set; }
    }
}

Shop/ViewModels/ShopCartViewModel.cs
using Shop.Data.Models;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart ShopCart { get; set; }
    }
}

Shop/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Shop.Controllers
{
    public class CarsController : Controller
    {
        private readonly IAllCars _allCars;
        private readonly ICarsCategory _allCategories;

        public CarsController(IAllCars allCars, ICarsCategory carsCategory)
        {
            _allCars = allCars;
            _allCategories = carsCategory;
        }

        [Route("Cars/List")]
        [Route("Cars/List/{categoryParam}")]
        public ViewResult List(string categoryParam)
        {
            string category = categoryParam;
            IEnumerable<Car> cars;
            string currentCategory = "";

            if (string.IsNullOrEmpty(categoryParam))
            {
                cars = _allCars.Cars.OrderBy(index => index.Id);
            }
            else
            {
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(index => index.Category.CategoryName.
                    Equals("Электромобиль")).
                    OrderBy(index => index.Id);

                    currentCategory = "Электромобили";
				}
                else
                {
					cars = _allCars.Cars.Where(index => index.Category.CategoryName.
					Equals("Автомобиль")).
					OrderBy(index => index.Id);

                    currentCategory = "Автомобили";
				}
            }

            ViewBag.Title = "Автомобили";
            var carObject = new CarsListViewModel
            {
                allCars = cars,
                currentCategory = currentCategory,
            };

            return View(carObject);
        }
    }
}

Shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private IAllCars _carRepository;

        public HomeController(IAllCars carRepository)
        {
            _carRepository = carRepository;
        }

        public ViewResult Index()
        {
            var homeCars = new HomeViewModel
            {
                FavouriteCars = _carRepository.GetFavouriteCars
            };

            return View(homeCars);
        }
    }
}

Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using System;

namespace Shop.Controllers
{
	public class OrderController : Controller
	{
		private readonly IAllOrders _allOrders;
		private readonly ShopCart _shopCart;

		public OrderController(IAllOrders allOrders, ShopCart shopCart)
		{
			_allOrders = allOrders;
			_shopCart = shopCart;
		}

		public IActionResult Checkout()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Checkout(Order order)
		{
			_shopCart.ListShopItems = _shopCart.GetShopItems();

			if (_shopCart.ListShopItems.Count == 0)
			{
				ModelState.AddModelError("", "Товар отсутствует");
			}

			if (ModelState.IsValid)
			{
				_allOrders.CreateOrder(order);
				return RedirectToAction("Complete");
			}

			return View(order);
		}

		public IActionResult Complete()
		{
			ViewBag.Message = "Заказ обработан";

			return View();
		}
	}
}

Shop/Controllers/ShopCartController.cs
using Microsoft.IdentityModel.Tokens;
using Shop.Data.Repository;
using Shop.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Shop.ViewModels;
using System.Linq;
using Shop.Data.Interfaces;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRepository;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllCars carRepository, ShopCart shopCart)
        {
            _carRepository = carRepository;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;

            var obj = new ShopCartViewModel
            {
                ShopCart = _shopCart,
            };

            return View(obj);
        }

        public RedirectToActionResult AddToCart(int id)
        {
            var item = _carRepository.Cars.FirstOrDefault(i => i.Id == id);

            if (item != null)
            {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction("Index");
        }
    }
}

Shop/Views/Cars/List.cshtml
<h1>Все автомобили</h1>
<h3>@Model.currentCategory</h3>

<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.allCars)
        {
            @Html.Partial("AllCars", car)
        }
    }
</div>

Shop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Лучшие автомобили</h1>
<div class="row mt-5 mb-2">
    @foreach (var car in Model.FavouriteCars)
    {
        @Html.Partial("AllCars", car)
    }

</div>

Shop/Views/Order/Checkout.cshtml
@model Order

<div class="row">
	<h3>Оформление заказа</h3>
	<form asp-action="Checkout" method="post" class="form-horizontal">
		<div class="form-group">
			<label asp-for="Name"></label>
			<div class="col-md-5">
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="SecondName"></label>
			<div class="col-md-5">
				<input asp-for="SecondName" class="form-control" />
				<span asp-validation-for="SecondName" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Adress"></label>
			<div class="col-md-5">
				<input asp-for="Adress" class="form-control" />
				<span asp-validation-for="Adress" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Phone"></label>
			<div class="col-md-5">
				<input asp-for="Phone" class="form-control" />
				<span asp-validation-for="Phone" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Email"></label>
			<div class="col-md-5">
				<input asp-for="Email" class="form-control" />
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>
		</div>
		<input class="btn btn-success mt-5" type="submit" value="Завершить заказ" />
	</form>
</div>

Shop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Shop/Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.Img" alt="@Model.Name" width="300px" height="250px" />
    <h2>Модель: @Model.Name</h2>
    <p>@Model.ShortDescription</p>
    <p>Цена: @Model.Price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="AddToCart" asp-route-id="@Model.Id">Добавить в корзину</a></p>
</div>

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Auto-Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List">Все автомобили</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/electro">Электромобили</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/fuel">Бензиновые автомобили</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Корзина</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2022-2023 Гайдукевич К. И. <a href="#">Соглашение</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

Shop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel

<div class="container">
    @foreach (var item in Model.ShopCart.ListShopItems)
    {
        <div class="alert alert-warning mt-3">
            <b>Автомобиль: </b> @item.Car.Name <br/>
            <b>Цена: </b> @item.Car.Price.ToString("c")
        </div>
    }
    <hr />
    <a class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Оплатить</a>
</div>